baseURL = 'http://www.brch.sk/'
languageCode = 'en-us'
title = 'brch'
theme='mini'


paginate = 3

disqusShortname = "brch"

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[social]
github = "https://github.com/nodejh"
twitter = "https://github.com/nodejh"
stackoverflow = "https://stackoverflow.com/users/4518882/nodejh"

[params]
author = "brch"
bio = "Software Engineer"

businessName = "brch s.r.o"
businessNameFull = "Názov spoločnosti : brch s.r.o"
createdAt = "Established : November 2022"
address = "Adresa : Laurinská 3, Bratislava, 811 01"
country = "Krajina : Slovenská republika"
mail = "Mail : info@brch.sk"
dic = "DIČ : 2121857243"
ico = "IČO : 55009492"
icodph=  "IČ DPH : SK2121857243"

description = "brch s.r.o | AI software company"
enableRSS = false
enableComments = false
enableGoogleAnalytics = false
