name: Websupport deploy

on:
  push:
    branches:
      - main  # Set a branch to deploy

jobs:
  build:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.106.0'
          # extended: true

      - name: Build
        run: hugo --minify
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
            server: brch.sk
            username: w.brch.sk
            password: ${{ secrets.FTP_PASS }}
            local-dir: ./public/